# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(935, 550)
        MainWindow.setMinimumSize(QtCore.QSize(935, 550))
        MainWindow.setMaximumSize(QtCore.QSize(935, 550))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 30, 181, 326))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.check_serial_Button = QtWidgets.QPushButton(self.groupBox)
        self.check_serial_Button.setObjectName("check_serial_Button")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.check_serial_Button)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.chose_port_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.chose_port_comboBox.setObjectName("chose_port_comboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.chose_port_comboBox)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_3)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comboBox_4)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.comboBox_5)
        self.open_serial_Button = QtWidgets.QPushButton(self.groupBox)
        self.open_serial_Button.setStyleSheet("background-color:rgb(255, 87, 58)")
        self.open_serial_Button.setObjectName("open_serial_Button")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.open_serial_Button)
        self.close_serial_Button = QtWidgets.QPushButton(self.groupBox)
        self.close_serial_Button.setObjectName("close_serial_Button")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.close_serial_Button)
        self.statues = QtWidgets.QLabel(self.groupBox)
        self.statues.setTextFormat(QtCore.Qt.AutoText)
        self.statues.setObjectName("statues")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.statues)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 362, 181, 132))
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.recived_data_num = QtWidgets.QLineEdit(self.groupBox_2)
        self.recived_data_num.setMinimumSize(QtCore.QSize(0, 0))
        self.recived_data_num.setObjectName("recived_data_num")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.recived_data_num)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.sent_data_num = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sent_data_num.sizePolicy().hasHeightForWidth())
        self.sent_data_num.setSizePolicy(sizePolicy)
        self.sent_data_num.setObjectName("sent_data_num")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sent_data_num)
        self.clear_all_Button = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_all_Button.sizePolicy().hasHeightForWidth())
        self.clear_all_Button.setSizePolicy(sizePolicy)
        self.clear_all_Button.setObjectName("clear_all_Button")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.clear_all_Button)
        self.sent_Box = QtWidgets.QGroupBox(self.centralwidget)
        self.sent_Box.setGeometry(QtCore.QRect(240, 368, 525, 142))
        self.sent_Box.setObjectName("sent_Box")
        self.sent_textEdit = QtWidgets.QTextEdit(self.sent_Box)
        self.sent_textEdit.setGeometry(QtCore.QRect(19, 27, 499, 112))
        self.sent_textEdit.setObjectName("sent_textEdit")
        self.sent_text_Button = QtWidgets.QPushButton(self.centralwidget)
        self.sent_text_Button.setGeometry(QtCore.QRect(800, 400, 93, 28))
        self.sent_text_Button.setObjectName("sent_text_Button")
        self.clear_text_Button = QtWidgets.QPushButton(self.centralwidget)
        self.clear_text_Button.setGeometry(QtCore.QRect(800, 460, 93, 28))
        self.clear_text_Button.setObjectName("clear_text_Button")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(240, 0, 671, 361))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 661, 331))
        self.layoutWidget.setObjectName("layoutWidget")
        self.graph_Layout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.graph_Layout.setContentsMargins(0, 0, 0, 0)
        self.graph_Layout.setObjectName("graph_Layout")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.receive_textEdit = QtWidgets.QTextEdit(self.tab_2)
        self.receive_textEdit.setGeometry(QtCore.QRect(0, 0, 551, 331))
        self.receive_textEdit.setObjectName("receive_textEdit")
        self.clear_receive_button = QtWidgets.QPushButton(self.tab_2)
        self.clear_receive_button.setGeometry(QtCore.QRect(560, 240, 93, 28))
        self.clear_receive_button.setObjectName("clear_receive_button")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 935, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comboBox_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "串口设置"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">串口检测</p></body></html>"))
        self.check_serial_Button.setText(_translate("MainWindow", "检测串口"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">串口选择</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\">波特率:</p></body></html>"))
        self.comboBox_2.setCurrentText(_translate("MainWindow", "9600"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "9600"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "2400"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "4800"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "12800"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "14400"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "19200"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "38400"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "57600"))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "76800"))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "115200"))
        self.comboBox_2.setItemText(10, _translate("MainWindow", "230400"))
        self.comboBox_2.setItemText(11, _translate("MainWindow", "460800"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\">数据位：</p></body></html>"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "8"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "7"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "6"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "5"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\">校验位:</p></body></html>"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "N"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\">停止位:</p></body></html>"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "1.5"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "2"))
        self.open_serial_Button.setText(_translate("MainWindow", "打开串口"))
        self.close_serial_Button.setText(_translate("MainWindow", "关闭串口"))
        self.statues.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ff0000;\"><br/></span></p></body></html>"))
        self.groupBox_2.setTitle(_translate("MainWindow", "串口状态(未打开)"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\">已接受:</p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "已发送:"))
        self.clear_all_Button.setText(_translate("MainWindow", "清空数据"))
        self.sent_Box.setTitle(_translate("MainWindow", "发送区"))
        self.sent_text_Button.setText(_translate("MainWindow", "发送"))
        self.clear_text_Button.setText(_translate("MainWindow", "清除"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "图形"))
        self.clear_receive_button.setText(_translate("MainWindow", "清除"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "文字"))
